version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: servicio
  db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    container_name: db
    env_file:
      - ./.env
    volumes:
      - volumendb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8082:80"
    container_name: myphpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  volumendb:      