version: '3.8'
services:
  service-a1:
    build: ./service-a   
    ports:
      - "4000:4000"
    networks:
      - mired  
  service-b1:
    build: ./service-b    
    ports:
      - "4001:4001"    
    networks:
      - mired
networks:
  mired:        
        