version: '3.8'
services:
  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./entorno:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes    